# Generated by Django 2.1.5 on 2019-01-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Рейс', 'verbose_name_plural': 'Рейсы'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'польователи'},
        ),
        migrations.AlterField(
            model_name='flight',
            name='arr_point',
            field=models.CharField(max_length=50, verbose_name='Место прибытия'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arr_time',
            field=models.DateTimeField(verbose_name='Время пибытия'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dep_point',
            field=models.CharField(max_length=50, verbose_name='Место отправления'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dep_time',
            field=models.DateTimeField(verbose_name='Время вылета'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Данные удостоверения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='third_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, verbose_name='Логи'),
        ),
        migrations.AlterModelTable(
            name='flight',
            table='fights',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='tickets',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
