# Generated by Django 2.1.5 on 2019-01-11 21:14

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('app1', '0004_auto_20190112_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_fly',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
