# Generated by Django 2.1.5 on 2019-01-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_mediamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(blank=True, upload_to='user_media/')),
            ],
        ),
        migrations.DeleteModel(
            name='MediaModel',
        ),
    ]
